# .github/workflows/validate-blueprints.yml
name: Validate Home Assistant blueprints

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  lint-blueprints:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 🚀 Run yamllint on blueprints
        uses: frenck/action-yamllint@v1
        with:
          config: ".yamllint"
          strict: true
          path: "blueprints/"
