name: Validate Blueprints
on: 
  push:
    paths: ['blueprints/**']
  pull_request:
    paths: ['blueprints/**']

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate Blueprints
      uses: home-assistant/actions/blueprint-lint@v1.0
      with:
        path: blueprints/
